Задача 1: Найдите всех женщин с IP-адресом, начинающимся на "1" и вывести их полные имена

Задача 2:  Создайте новый столбец domain, который будет содержать домен из электронной почты (например, для zsheara0@buzzfeed.com домен — buzzfeed.com).

Задача 3: Найдите все уникальные домены из столбца domain

Задача 4. Анализ возраста (если бы он был)
Задача:
- Добавьте столбец с возрастом (случайные значения от 18 до 65).
- Разделите пользователей на возрастные группы: 18-25, 26-35, 36-50, 51+.
- Подсчитайте количество пользователей в каждой группе.
- Найдите средний возраст для каждой группы.

In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('hw_DE_12.csv')
df

,id,first_name,last_name,email,gender,ip_address
0,1,Zebulon,Sheara,zsheara0@buzzfeed.com,Male,26.254.115.173
1,2,Gabby,Hundy,ghundy1@dyndns.org,Male,86.222.142.186
2,3,Zaneta,Macewan,zmacewan2@dyndns.org,Female,20.98.185.65
3,4,Linn,Steely,lsteely3@psu.edu,Male,65.253.237.106
4,5,Althea,Segar,asegar4@prlog.org,Female,25.127.235.34
...,...,...,...,...,...,...
995,996,Zsa zsa,McGarahan,zmcgarahanrn@craigslist.org,Female,208.135.43.154
996,997,Al,Villiers,avilliersro@nydailynews.com,Agender,168.3.4.142
997,998,Natalina,Clavering,nclaveringrp@jugem.jp,Female,16.223.145.44
998,999,Gretta,Witheford,gwithefordrq@discovery.com,Female,61.83.241.246
999,1000,Tadio,Feighney,tfeighneyrr@google.es,Male,154.243.103.8

In [13]:
df_filtered = df[(df['gender'] == 'Female') & (df['ip_address'].str.startswith('1'))]
df_filtered

,id,first_name,last_name,email,gender,ip_address
8,9,Kaile,Clementson,kclementson8@rediff.com,Female,147.21.239.61
10,11,Melosa,Boneham,mbonehama@quantcast.com,Female,176.120.71.216
11,12,Deina,Frisdick,dfrisdickb@bbc.co.uk,Female,146.176.89.94
15,16,Mamie,Wainwright,mwainwrightf@studiopress.com,Female,163.100.199.174
25,26,Ysabel,Aitchinson,yaitchinsonp@woothemes.com,Female,162.207.227.183
...,...,...,...,...,...,...
980,981,Pennie,Itzhaki,pitzhakir8@wiley.com,Female,186.15.175.207
984,985,Lula,Almon,lalmonrc@nationalgeographic.com,Female,142.209.10.99
989,990,Francesca,Shorrock,fshorrockrh@creativecommons.org,Female,168.4.169.89
993,994,Morganica,Pierton,mpiertonrl@epa.gov,Female,150.213.150.57
997,998,Natalina,Clavering,nclaveringrp@jugem.jp,Female,16.223.145.44

In [14]:
df['domain'] = df['email'].str.split('@').str[1]
df

,id,first_name,last_name,email,gender,ip_address,domain
0,1,Zebulon,Sheara,zsheara0@buzzfeed.com,Male,26.254.115.173,buzzfeed.com
1,2,Gabby,Hundy,ghundy1@dyndns.org,Male,86.222.142.186,dyndns.org
2,3,Zaneta,Macewan,zmacewan2@dyndns.org,Female,20.98.185.65,dyndns.org
3,4,Linn,Steely,lsteely3@psu.edu,Male,65.253.237.106,psu.edu
4,5,Althea,Segar,asegar4@prlog.org,Female,25.127.235.34,prlog.org
...,...,...,...,...,...,...,...
995,996,Zsa zsa,McGarahan,zmcgarahanrn@craigslist.org,Female,208.135.43.154,craigslist.org
996,997,Al,Villiers,avilliersro@nydailynews.com,Agender,168.3.4.142,nydailynews.com
997,998,Natalina,Clavering,nclaveringrp@jugem.jp,Female,16.223.145.44,jugem.jp
998,999,Gretta,Witheford,gwithefordrq@discovery.com,Female,61.83.241.246,discovery.com
999,1000,Tadio,Feighney,tfeighneyrr@google.es,Male,154.243.103.8,google.es

In [18]:
df['domain'].unique()

array(['buzzfeed.com', 'dyndns.org', 'psu.edu', 'prlog.org',
       'mozilla.org', 'eepurl.com', 'github.io', 'rediff.com',
       'newsvine.com', 'quantcast.com', 'bbc.co.uk', 'squarespace.com',
       'si.edu', 'about.com', 'studiopress.com', 'wufoo.com',
       'cornell.edu', 'jiathis.com', 'walmart.com', 'aboutads.info',
       'simplemachines.org', 'flavors.me', 'hostgator.com', 'baidu.com',
       'woothemes.com', 'networksolutions.com', 'redcross.org',
       'globo.com', 'nhs.uk', 'sogou.com', 'berkeley.edu', 'fotki.com',
       'sitemeter.com', 'ifeng.com', 'bloglovin.com', 'google.com.hk',
       'soup.io', 'vkontakte.ru', 'accuweather.com', 'springer.com',
       'npr.org', 'addtoany.com', 'dailymotion.com', 'sciencedirect.com',
       'wikia.com', 'apache.org', 'youku.com', 'toplist.cz', 'tmall.com',
       'blinklist.com', 'phoca.cz', 'abc.net.au', 'indiegogo.com',
       'istockphoto.com', 'sbwire.com', 'economist.com', 'usatoday.com',
       'netlog.com', 'blogspot.com', 'drupal.org', 'harvard.edu', 'ow.ly',
       'usgs.gov', 'mlb.com', 'answers.com', 'instagram.com', 'uiuc.edu',
       'a8.net', 'stanford.edu', 'columbia.edu', 'devhub.com', 'tiny.cc',
       'irs.gov', 'dropbox.com', 'latimes.com', 'wp.com', 'is.gd',
       'themeforest.net', 'barnesandnoble.com', 'jalbum.net', 'yale.edu',
       'home.pl', 'mac.com', 'over-blog.com', 'biblegateway.com',
       'google.it', 'technorati.com', 'craigslist.org', 'clickbank.net',
       'edublogs.org', 'de.vu', 'princeton.edu', 'cisco.com', 'slate.com',
       'dot.gov', 'php.net', 'rambler.ru', 'un.org', 'foxnews.com',
       'github.com', 'nih.gov', 'tripod.com', 'digg.com', 'zdnet.com',
       'networkadvertising.org', 'ustream.tv', 'newyorker.com', 'icio.us',
       'mayoclinic.com', 'goo.ne.jp', 'qq.com', 'loc.gov',
       'chicagotribune.com', 'japanpost.jp', 'cbsnews.com', 'nps.gov',
       'scribd.com', 'google.co.jp', 'guardian.co.uk', 'amazonaws.com',
       'gmpg.org', 'reddit.com', 'wikipedia.org', 'csmonitor.com',
       'angelfire.com', 'w3.org', 'g.co', 'zimbio.com', 'virginia.edu',
       'smugmug.com', 'typepad.com', 'pen.io', 'xing.com', 'gravatar.com',
       'adobe.com', 'oaic.gov.au', 'unc.edu', 'google.com.br',
       'biglobe.ne.jp', 'photobucket.com', 'myspace.com', 'java.com',
       'ucsd.edu', 'state.tx.us', 'cbc.ca', 'naver.com', 'blog.com',
       'hubpages.com', 'merriam-webster.com', 'freewebs.com',
       'bizjournals.com', 'state.gov', 'discuz.net', 'skyrock.com',
       'bigcartel.com', 'linkedin.com', 'msn.com', 'statcounter.com',
       'yandex.ru', 'utexas.edu', 'omniture.com', 'spotify.com',
       'theatlantic.com', 'acquirethisname.com', 'cloudflare.com',
       'com.com', 'nsw.gov.au', 'hp.com', 'hud.gov', 'marketwatch.com',
       'godaddy.com', 'about.me', 'microsoft.com', 'jugem.jp',
       'salon.com', 'oakley.com', 'imdb.com', 'patch.com', 'ft.com',
       'shareasale.com', 'ed.gov', 'desdev.cn', 'china.com.cn',
       'house.gov', 'elpais.com', 'shinystat.com', 'yahoo.co.jp',
       '1und1.de', 'gov.uk', 'wired.com', 'people.com.cn', 'nifty.com',
       'sourceforge.net', 'google.com.au', 'smh.com.au', 'bravesites.com',
       'google.nl', 'google.co.uk', 'cnet.com', 'histats.com',
       'sphinn.com', 'census.gov', 'goodreads.com', '123-reg.co.uk',
       'cdc.gov', 'exblog.jp', 'deliciousdays.com', 'ucoz.ru',
       'symantec.com', 'booking.com', 'alibaba.com', 'sun.com',
       'constantcontact.com', 'netscape.com', 'webeden.co.uk',
       'hao123.com', 'usda.gov', 'time.com', 'dedecms.com', 'go.com',
       'example.com', 'dailymail.co.uk', 'oracle.com',
       'pagesperso-orange.fr', 'flickr.com', 'storify.com',
       'wikimedia.org', 'ucla.edu', 'rakuten.co.jp', 'multiply.com',
       'theglobeandmail.com', 'bloglines.com', 't-online.de',
       'cargocollective.com', 'tamu.edu', 'ycombinator.com',
       'weather.com', 'nba.com', 'twitter.com', 'wix.com', 'marriott.com',
       'reference.com', 'e-recht24.de', 'homestead.com', 'jimdo.com',
       'ted.com', 'nytimes.com', 'joomla.org', 'nyu.edu', 'imgur.com',
       'feedburner.com', 'cnn.com', 'businessweek.com', 'cnbc.com',
       'sina.com.cn', 'wsj.com', 'webmd.com', 'skype.com', 'behance.net',
       'noaa.gov', 'bluehost.com', 'google.ca', 'gizmodo.com', 'ftc.gov',
       'xrea.com', 'furl.net', 'dmoz.org', 'addthis.com', 'youtube.com',
       'surveymonkey.com', 'umich.edu', 'arstechnica.com',
       'tripadvisor.com', 'ibm.com', 'boston.com', 'bing.com', '163.com',
       'wordpress.com', 'engadget.com', 'gnu.org', 'twitpic.com',
       'vk.com', 'ucoz.com', 'ihg.com', 'weibo.com', 'nbcnews.com',
       'who.int', 'cocolog-nifty.com', 'delicious.com', 'prweb.com',
       'mashable.com', 'washingtonpost.com', 'theguardian.com',
       'altervista.org', 'howstuffworks.com', 'timesonline.co.uk',
       'hugedomains.com', 'stumbleupon.com', 'ca.gov', 'mail.ru',
       'nymag.com', 'etsy.com', 'reverbnation.com', 'ox.ac.uk', 'fda.gov',
       'aol.com', 'europa.eu', 'cyberchimps.com', 'sohu.com',
       'businesswire.com', 'slideshare.net', 'parallels.com', 'ebay.com',
       'reuters.com', 'amazon.co.uk', 'ehow.com', 'uol.com.br',
       'miibeian.gov.cn', 'upenn.edu', 'nydailynews.com', 'hc360.com',
       'narod.ru', 'liveinternet.ru', 'vinaora.com', 'opera.com',
       'dagondesign.com', 'ezinearticles.com', 'issuu.com', 'amazon.de',
       'yahoo.com', 'tuttocitta.it', 'epa.gov', 'pinterest.com',
       'ebay.co.uk', 'live.com', 'seesaa.net', 'plala.or.jp', 'webs.com',
       'macromedia.com', 'weebly.com', 'wiley.com', 'hhs.gov', 'fc2.com',
       'tumblr.com', 'hexun.com', 'cbslocal.com', 'prnewswire.com',
       'paginegialle.it', 'cdbaby.com', 'list-manage.com',
       'deviantart.com', 'shutterfly.com', '4shared.com',
       'creativecommons.org', 'intel.com', 'amazon.co.jp',
       'fastcompany.com', 'dion.ne.jp', 'i2i.jp', 'meetup.com',
       'illinois.edu', 'bloomberg.com', 'whitehouse.gov',
       'washington.edu', 'so-net.ne.jp', 'phpbb.com', 'vimeo.com',
       'yellowpages.com', 'comsenz.com', 'ameblo.jp', '1688.com',
       'privacy.gov.au', 'friendfeed.com', 'blogs.com', 'unicef.org',
       'disqus.com', 'bandcamp.com', 'auda.org.au', 'paypal.com',
       'discovery.com', 'nature.com', 'slashdot.org', 'cpanel.net',
       'google.fr', 'hatena.ne.jp', 'mediafire.com', 'mit.edu',
       'eventbrite.com', 'facebook.com', 'mtv.com', 'printfriendly.com',
       'moonfruit.com', 'businessinsider.com', 'fema.gov', 'apple.com',
       'ocn.ne.jp', 'topsy.com', 'usnews.com', 'imageshack.us',
       'geocities.com', 'pcworld.com', 'mapquest.com', 'mapy.cz',
       'ask.com', 'cafepress.com', 'google.ru', 'army.mil', 'archive.org',
       'icq.com', 'ovh.net', 'netvibes.com', 'google.pl', 'hibu.com',
       'pbs.org', 'ning.com', 'examiner.com', 'jigsy.com', 't.co',
       'usa.gov', 'chron.com', 'lulu.com', 'huffingtonpost.com',
       'xinhuanet.com', 'livejournal.com', 'last.fm', 'samsung.com',
       'blogtalkradio.com', 'yelp.com', 'google.de', 'msu.edu',
       'tinypic.com', 'taobao.com', 'nationalgeographic.com',
       'scientificamerican.com', 'google.es'], dtype=object)

In [43]:
df['age'] = np.random.randint(18, 66, size=len(df))
df

,id,first_name,last_name,email,gender,ip_address,domain,age,agegroup
0,1,Zebulon,Sheara,zsheara0@buzzfeed.com,Male,26.254.115.173,buzzfeed.com,44,51+
1,2,Gabby,Hundy,ghundy1@dyndns.org,Male,86.222.142.186,dyndns.org,49,36-50
2,3,Zaneta,Macewan,zmacewan2@dyndns.org,Female,20.98.185.65,dyndns.org,27,51+
3,4,Linn,Steely,lsteely3@psu.edu,Male,65.253.237.106,psu.edu,64,18-25
4,5,Althea,Segar,asegar4@prlog.org,Female,25.127.235.34,prlog.org,50,36-50
...,...,...,...,...,...,...,...,...,...
995,996,Zsa zsa,McGarahan,zmcgarahanrn@craigslist.org,Female,208.135.43.154,craigslist.org,52,26-35
996,997,Al,Villiers,avilliersro@nydailynews.com,Agender,168.3.4.142,nydailynews.com,52,36-50
997,998,Natalina,Clavering,nclaveringrp@jugem.jp,Female,16.223.145.44,jugem.jp,52,26-35
998,999,Gretta,Witheford,gwithefordrq@discovery.com,Female,61.83.241.246,discovery.com,51,51+
999,1000,Tadio,Feighney,tfeighneyrr@google.es,Male,154.243.103.8,google.es,19,51+

In [46]:
age_bins = [18, 25, 35, 50, 65]
age_labels = ['18-25', '26-35', '36-50', '51+']
df['agegroup'] = pd.cut(df['age'], bins=age_bins, labels=age_labels, right=True)
df

,id,first_name,last_name,email,gender,ip_address,domain,age,agegroup
0,1,Zebulon,Sheara,zsheara0@buzzfeed.com,Male,26.254.115.173,buzzfeed.com,44,36-50
1,2,Gabby,Hundy,ghundy1@dyndns.org,Male,86.222.142.186,dyndns.org,49,36-50
2,3,Zaneta,Macewan,zmacewan2@dyndns.org,Female,20.98.185.65,dyndns.org,27,26-35
3,4,Linn,Steely,lsteely3@psu.edu,Male,65.253.237.106,psu.edu,64,51+
4,5,Althea,Segar,asegar4@prlog.org,Female,25.127.235.34,prlog.org,50,36-50
...,...,...,...,...,...,...,...,...,...
995,996,Zsa zsa,McGarahan,zmcgarahanrn@craigslist.org,Female,208.135.43.154,craigslist.org,52,51+
996,997,Al,Villiers,avilliersro@nydailynews.com,Agender,168.3.4.142,nydailynews.com,52,51+
997,998,Natalina,Clavering,nclaveringrp@jugem.jp,Female,16.223.145.44,jugem.jp,52,51+
998,999,Gretta,Witheford,gwithefordrq@discovery.com,Female,61.83.241.246,discovery.com,51,51+
999,1000,Tadio,Feighney,tfeighneyrr@google.es,Male,154.243.103.8,google.es,19,18-25

In [47]:
df.groupby('agegroup', observed=True).size()

agegroup
18-25    137
26-35    199
36-50    316
51+      327
dtype: int64

In [48]:
df.groupby('agegroup', observed=True)['age'].mean()

agegroup
18-25    21.883212
26-35    30.532663
36-50    42.702532
51+      57.724771
Name: age, dtype: float64